### ISSUE TITLE
Chord Chart

### ISSUE THREAD

**Issue by JoshSchoen** [Teradata/covalent-coding-standards-nightly#16]
## Feature Request
Not available in the v3/v4 examples but found it in the v2 examples.
http://echarts.baidu.com/echarts2/doc/example/chord3.html#-en

### Component Considerations
- Series component
- Series tooltips atomic implementations
- interfaces to describe the configuration options for good dev UX.

**Comment by JoshSchoen** [comment]
@jeremysmartt I don't think so as the paths thickness normally have some meaning in chord chart like this. There's also some highlight/focusing features that the graph type are missing. There is also a chord chart defined in the echarts repo as well https://github.com/apache/incubator-echarts/tree/master/src/chart/chord so I'm thinking it's a really chart type just not in the v4 examples. I'll throw a stackblitz together to confirm with the config JS object and we'll see what we get. How does that sound?

**Comment by jeremysmartt** [comment]
oh i see, thanks @JoshSchoen

**Comment by emoralesb05** [comment]
Yeah, looks like the implementation is not proper.. ive been looking into the examples to see how to extend the echarts library. So it might be good to see at examples like wordcloud extentions and such incase we need to add our own implementations of certain charts.
